let button1 = document.getElementById("one")

console.log(button1.value)
button1.addEventListener("click", () => {
    console.log("Button One Close")
    nav.classList.add("remove-navbar")
    nav.classList.remove("add-navbar")
})


let button2 = document.getElementById("two")

console.log(button2.value)
button2.addEventListener("click", () => {
    console.log("Display nav")
    nav.classList.add("add-navbar")
    nav.classList.remove("remove-navbar")
})


let button3 = document.getElementById("three")
let button4 = document.getElementById("four")
let button5 = document.getElementById("five")
let button6 = document.getElementById("six")
let button7 = document.getElementById("seven")
let button8 = document.getElementById("eight")
let button9 = document.getElementById("nine")
let button10 = document.getElementById("ten")
let button11 = document.getElementById("eleven")
let button12 = document.getElementById("twelve")
let button13 = document.getElementById("thirteen")
let button14 = document.getElementById("fourteen")



console.log(button3.innerHTML)
button3.addEventListener("click", () => {
    console.log("Button Three Clicked")
    button3.classList.add("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button4.innerHTML)
button4.addEventListener("click", () => {
    console.log("Button Four Clicked")
    button3.classList.remove("active")
    button4.classList.add("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button5.innerHTML)
button5.addEventListener("click", () => {
    console.log("Button Five Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.add("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button6.innerHTML)
button6.addEventListener("click", () => {
    console.log("Button Six Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.add("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button7.innerHTML)
button7.addEventListener("click", () => {
    console.log("Button Seven Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.add("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button8.innerHTML)
button8.addEventListener("click", () => {
    console.log("Button Eight Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.add("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button9.innerHTML)
button9.addEventListener("click", () => {
    console.log("Button Nine Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.add("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button10.innerHTML)
button10.addEventListener("click", () => {
    console.log("Button Ten Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.add("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button11.innerHTML)
button11.addEventListener("click", () => {
    console.log("Button Eleven Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.add("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button12.innerHTML)
button12.addEventListener("click", () => {
    console.log("Button Twelve Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.add("active")
    button13.classList.remove("active")
    button14.classList.remove("active")
})

console.log(button13.innerHTML)
button13.addEventListener("click", () => {
    console.log("Button Thirteen Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.add("active")
    button14.classList.remove("active")
})

console.log(button14.innerHTML)
button14.addEventListener("click", () => {
    console.log("Button Fourteen Clicked")
    button3.classList.remove("active")
    button4.classList.remove("active")
    button5.classList.remove("active")
    button6.classList.remove("active")
    button7.classList.remove("active")
    button8.classList.remove("active")
    button9.classList.remove("active")
    button10.classList.remove("active")
    button11.classList.remove("active")
    button12.classList.remove("active")
    button13.classList.remove("active")
    button14.classList.add("active")
})